version: '3.3'


networks:
  openherbarium:
    driver: bridge

services:
    build: _thumbnailservice/
    ports:
          - 7080:7080
          - 7081:7081

    volumes:
          - ./../../rest/endpoint/target/herbarium-m-app-srv-metadatasrv-rest-endpoint-0.0.1-SNAPSHOT.jar:/app/fat.jar
    networks:
          - openherbarium
