# Use postgres/example user/password credentials
version: '3.3'


networks:
  openherbarium:
    driver: bridge


services:
#    db:
#        image: postgres:alpine
#        restart: always
#
#        ports:
#              - 5432:5432
#        environment:
#            POSTGRES_PASSWORD: admin
#
#
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - 8080:9999

  postgres:
    build: _postgresql/
    ports:
          - 5432:5432
    volumes:
          - ./_postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - openherbarium

  metadataservice:
    build: _metadataservice/
    ports:
          - 7080:7080
          - 7081:7081

    volumes:
          - ./../../rest/endpoint/target/herbarium-m-app-srv-metadatasrv-rest-endpoint-0.0.1-SNAPSHOT.jar:/app/fat.jar
    networks:
          - openherbarium

    depends_on:
      - postgres

    links:
      - postgres